"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, BarChart3, Fuel, LoaderCircle, RefreshCw, Trash2 } from "lucide-react";
import { deleteDewatering, deleteHauling, deleteLoading, deleteSupporting, fetchDewateringSummaries, fetchHaulingSummaries, fetchLoadingSummaries, fetchSupportingSummaries } from "@/lib/api";
import type { DewateringSummary, HaulingSummary, LoadingSummary, SupportingSummary } from "@/types/api";
import { DataTablePagination, DataTableSearch, SortableHeader, type SortDirection } from "@/components/ui/data-table";
import { toast } from "@/components/ui/toast";

type ActivityName = "Loading" | "Hauling" | "Supporting" | "Dewatering";
type SortKey = "activity" | "unitType" | "fuelType" | "fuel" | "production" | "fuelRatio";
interface ActivityRow { id: string; transactionId: number; activity: ActivityName; unitType: string; fuelType: string; fuel: number; production: number; fuelRatio: number; }
const pageSize = 10;
const style: Record<ActivityName, string> = { Loading: "bg-amber-50 text-amber-700", Hauling: "bg-cyan-50 text-cyan-700", Supporting: "bg-violet-50 text-violet-700", Dewatering: "bg-emerald-50 text-emerald-700" };
const number = (value: number, digits = 0) => value.toLocaleString("id-ID", { maximumFractionDigits: digits });
const toRows = (loading: LoadingSummary[], hauling: HaulingSummary[], supporting: SupportingSummary[], dewatering: DewateringSummary[]): ActivityRow[] => [
  ...loading.map((item) => ({ id: `loading-${item.id}`, transactionId: item.loading_id, activity: "Loading" as const, unitType: item.unit_type, fuelType: item.fuel_type, fuel: item.fuel_cons_actual ?? item.fuel_cons, production: item.productivity, fuelRatio: item.fuel_ratio_actual ?? item.fuel_ratio })),
  ...hauling.map((item) => ({ id: `hauling-${item.id}`, transactionId: item.hauling_id, activity: "Hauling" as const, unitType: item.unit_type, fuelType: item.fuel_type, fuel: item.fuel_cons_actual ?? item.fuel_cons, production: item.productivity, fuelRatio: item.fuel_ratio_actual ?? item.fuel_ratio })),
  ...supporting.map((item) => ({ id: `supporting-${item.id}`, transactionId: item.supporting_id, activity: "Supporting" as const, unitType: item.unit_type, fuelType: item.fuel_type, fuel: item.total_fuel_liters, production: item.total_mine_prod_bcm, fuelRatio: item.fuel_ratio_actual ?? item.fuel_ratio })),
  ...dewatering.map((item) => ({ id: `dewatering-${item.id}`, transactionId: item.dewatering_id, activity: "Dewatering" as const, unitType: item.unit_type, fuelType: item.fuel_type, fuel: item.total_fuel_liters, production: item.total_mine_prod_bcm, fuelRatio: item.fuel_ratio_actual ?? item.fuel_ratio })),
];

export function ActivityFuelConsumption() {
  const [items, setItems] = useState<ActivityRow[]>([]); const [activity, setActivity] = useState<ActivityName | "ALL">("ALL"); const [query, setQuery] = useState(""); const [sortKey, setSortKey] = useState<SortKey>("activity"); const [sortDirection, setSortDirection] = useState<SortDirection>("asc"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const result = await Promise.all([fetchLoadingSummaries(), fetchHaulingSummaries(), fetchSupportingSummaries(), fetchDewateringSummaries()]); setItems(toRows(...result)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Data konsumsi fuel tidak dapat dimuat."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const toggleSort = (key: SortKey) => { setSortDirection((value) => sortKey === key && value === "asc" ? "desc" : "asc"); setSortKey(key); setPage(1); };
  const rows = useMemo(() => items.filter((row) => (activity === "ALL" || row.activity === activity) && `${row.activity} ${row.unitType} ${row.fuelType}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => { const first = a[sortKey]; const second = b[sortKey]; const result = typeof first === "number" && typeof second === "number" ? first - second : String(first).localeCompare(String(second), "id", { numeric: true }); return result * (sortDirection === "asc" ? 1 : -1); }), [activity, items, query, sortDirection, sortKey]);
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize)); const visibleRows = rows.slice((Math.min(page, pageCount) - 1) * pageSize, Math.min(page, pageCount) * pageSize); const totalFuel = rows.reduce((total, row) => total + row.fuel, 0); const totalProduction = rows.reduce((total, row) => total + row.production, 0);
  const remove = async (row: ActivityRow) => { if (!window.confirm(`Hapus transaksi ${row.activity} untuk ${row.unitType}?`)) return; try { if (row.activity === "Loading") await deleteLoading(row.transactionId); else if (row.activity === "Hauling") await deleteHauling(row.transactionId); else if (row.activity === "Supporting") await deleteSupporting(row.transactionId); else await deleteDewatering(row.transactionId); toast.add({ type: "success", title: "Transaksi dihapus", description: "Summary monitoring diperbarui." }); await load(); } catch (cause) { toast.add({ type: "error", title: "Gagal menghapus transaksi", description: cause instanceof Error ? cause.message : "Coba lagi." }); } };
  const header = (label: string, key: SortKey) => <SortableHeader label={label} align={key === "fuel" || key === "production" || key === "fuelRatio" ? "right" : "left"} active={sortKey === key} direction={sortDirection} onClick={() => toggleSort(key)} />;
  if (loading) return <div className="flex min-h-[520px] items-center justify-center rounded-2xl border border-slate-200 bg-white"><LoaderCircle className="size-7 animate-spin text-amber-500" /></div>;
  if (error) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center"><AlertTriangle className="mx-auto size-7 text-rose-500" /><h2 className="mt-3 font-bold text-rose-900">Konsumsi fuel tidak tersedia</h2><p className="mt-1 text-sm text-rose-700">{error}</p><button type="button" onClick={() => void load()} className="mt-4 rounded-xl bg-rose-700 px-4 py-2 text-xs font-semibold text-white">Coba lagi</button></div>;
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-600">Fitur 02 · Aktivitas</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Konsumsi Fuel Aktivitas</h2><p className="mt-1 text-sm text-slate-500">Pantau konsumsi aktual berdasarkan setiap transaksi operasional.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-sm"><RefreshCw className="size-3.5" />Perbarui data</button></section>
    <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Total Fuel</p><p className="mt-3 text-2xl font-bold text-slate-950">{number(totalFuel)} L</p><Fuel className="mt-3 size-5 text-cyan-600" /></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Total Produksi</p><p className="mt-3 text-2xl font-bold text-slate-950">{number(totalProduction)} BCM</p><BarChart3 className="mt-3 size-5 text-emerald-600" /></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Fuel Ratio</p><p className="mt-3 text-2xl font-bold text-slate-950">{(totalProduction ? totalFuel / totalProduction : 0).toFixed(3)} L/BCM</p><Activity className="mt-3 size-5 text-amber-600" /></div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div><h3 className="text-base font-bold text-slate-950">Detail Konsumsi Fuel</h3><div className="mt-3 flex flex-wrap gap-2">{(["ALL", "Loading", "Hauling", "Supporting", "Dewatering"] as const).map((value) => <button key={value} type="button" onClick={() => { setActivity(value); setPage(1); }} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${activity === value ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-500"}`}>{value === "ALL" ? "Semua" : value}</button>)}</div></div><DataTableSearch value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Cari aktivitas, unit, fuel..." /></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">{header("Aktivitas", "activity")}</th><th className="px-5 py-3">{header("Unit", "unitType")}</th><th className="px-5 py-3">{header("Fuel Reference", "fuelType")}</th><th className="px-5 py-3 text-right">{header("Fuel Aktual", "fuel")}</th><th className="px-5 py-3 text-right">{header("Produksi", "production")}</th><th className="px-5 py-3 text-right">{header("Fuel Ratio", "fuelRatio")}</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleRows.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${style[row.activity]}`}>{row.activity}</span></td><td className="px-5 py-4 font-semibold text-slate-800">{row.unitType}</td><td className="px-5 py-4 text-slate-500">{row.fuelType}</td><td className="px-5 py-4 text-right font-mono font-bold text-slate-800">{number(row.fuel)} L</td><td className="px-5 py-4 text-right font-mono text-slate-600">{number(row.production)} BCM</td><td className="px-5 py-4 text-right font-mono font-bold text-slate-800">{row.fuelRatio.toFixed(3)}</td><td className="px-5 py-4 text-right"><button type="button" onClick={() => void remove(row)} title="Hapus transaksi" className="rounded-xl border border-rose-200 bg-rose-50 p-2 text-rose-700 hover:bg-rose-100"><Trash2 className="size-3.5" /></button></td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-10 text-center text-sm text-slate-400">Tidak ada data yang sesuai.</p>}</div><DataTablePagination page={page} pageCount={pageCount} total={rows.length} pageSize={pageSize} onPageChange={setPage} /></section>
  </div>;
}
