"use client";

import { Building2, Eye, ShieldCheck } from "lucide-react";

export interface ContractorDetailRow { id: number; code: string; name: string; status: string; totalEquipment: number; loadingCount: number; haulingCount: number; supportingCount: number; dewateringCount: number; fuelConsLiters: number; totalBcmProd: number; fuelRatio: number | null; }
interface Props { data: ContractorDetailRow[]; selectedContractor: string; onSelectContractor: (code: string) => void; }

export function ContractorDetailTable({ data, selectedContractor, onSelectContractor }: Props) {
  const rows = selectedContractor === "ALL" ? data : data.filter((item) => item.code === selectedContractor);
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 backdrop-blur-sm"><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="flex items-center gap-2 text-lg font-bold text-white"><Building2 className="h-5 w-5 text-amber-400" />Matriks Performa Kontraktor</h2><p className="mt-1 text-xs text-slate-400">Klik baris untuk menampilkan armada kontraktor tersebut.</p></div><span className="rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs font-bold text-amber-400">{selectedContractor === "ALL" ? `${data.length} kontraktor` : selectedContractor}</span></div><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[920px] text-left text-xs"><thead className="border-b border-slate-800 bg-slate-950/70 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Kontraktor</th><th className="px-4 py-3 text-center">Armada</th><th className="px-4 py-3 text-center">Loading</th><th className="px-4 py-3 text-center">Hauling</th><th className="px-4 py-3 text-center">Supporting</th><th className="px-4 py-3 text-center">Dewatering</th><th className="px-4 py-3 text-right">BBM tercatat</th><th className="px-4 py-3 text-right">Produktivitas</th><th className="px-4 py-3 text-right">Fuel Ratio</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-800/60 text-slate-300">{rows.map((row) => <tr key={row.id} onClick={() => onSelectContractor(row.code)} className="cursor-pointer hover:bg-slate-950/40"><td className="px-4 py-3.5"><p className="font-semibold text-white">{row.name}</p><p className="font-mono text-[10px] text-slate-500">{row.code} · <span className="text-emerald-400">{row.status}</span></p></td><td className="px-4 py-3.5 text-center font-mono font-bold text-white">{row.totalEquipment}</td><td className="px-4 py-3.5 text-center font-mono text-amber-400">{row.loadingCount}</td><td className="px-4 py-3.5 text-center font-mono text-cyan-400">{row.haulingCount}</td><td className="px-4 py-3.5 text-center font-mono text-purple-400">{row.supportingCount}</td><td className="px-4 py-3.5 text-center font-mono text-emerald-400">{row.dewateringCount}</td><td className="px-4 py-3.5 text-right font-mono">{row.fuelConsLiters.toLocaleString("id-ID", { maximumFractionDigits: 0 })} L</td><td className="px-4 py-3.5 text-right font-mono">{row.totalBcmProd.toLocaleString("id-ID", { maximumFractionDigits: 1 })} BCM/jam</td><td className="px-4 py-3.5 text-right font-mono font-bold text-white">{row.fuelRatio === null ? "—" : `${row.fuelRatio.toFixed(3)} L/BCM`}</td><td className="px-4 py-3.5"><Eye className="h-4 w-4 text-slate-500" /></td></tr>)}</tbody></table></div><p className="mt-3 flex items-center gap-1.5 text-[11px] text-slate-500"><ShieldCheck className="h-3.5 w-3.5" />Tidak ada status lulus/gagal karena target SPO belum dikirim API.</p></section>;
}
