"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Check, Fuel, LoaderCircle, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { createFuelReference, deleteFuelReference, fetchFuelReferences, updateFuelReference } from "@/lib/api";
import type { FuelReference, FuelReferenceCreateInput } from "@/types/api";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { DataTablePagination, DataTableSearch, SortableHeader, type SortDirection } from "@/components/ui/data-table";
import { toast } from "@/components/ui/toast";

const blank: FuelReferenceCreateInput = { merk: "", type: "", activity: "loading", average: 0, low: 0, mid: 0, high: 0 };
const activities = ["loading", "hauling", "supporting", "dewatering"];
const number = (value: number) => value.toLocaleString("id-ID", { maximumFractionDigits: 2 });
const pageSize = 10;
type SortKey = "type" | "activity" | "average";

export function MasterFuelReferencesClient() {
  const [items, setItems] = useState<FuelReference[]>([]);
  const [form, setForm] = useState<FuelReferenceCreateInput>(blank);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [sortKey, setSortKey] = useState<SortKey>("type");
  const [sortDirection, setSortDirection] = useState<SortDirection>("asc");
  const [page, setPage] = useState(1);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await fetchFuelReferences()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Fuel reference tidak dapat dimuat."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const reset = () => { setForm(blank); setEditingId(null); };
  const toggleSort = (key: SortKey) => { setSortDirection((value) => sortKey === key && value === "asc" ? "desc" : "asc"); setSortKey(key); setPage(1); };
  const rows = useMemo(() => items.filter((item) => `${item.type} ${item.merk} ${item.activity}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (typeof a[sortKey] === "number" ? Number(a[sortKey]) - Number(b[sortKey]) : String(a[sortKey]).localeCompare(String(b[sortKey]))) * (sortDirection === "asc" ? 1 : -1)), [items, query, sortDirection, sortKey]);
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize));
  const visibleRows = rows.slice((Math.min(page, pageCount) - 1) * pageSize, Math.min(page, pageCount) * pageSize);
  const edit = (row: FuelReference) => { setEditingId(row.id); setForm({ merk: row.merk, type: row.type, activity: row.activity, average: row.average, low: row.low, mid: row.mid, high: row.high }); setError(null); setOpen(true); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(null); try { const input = { ...form, merk: form.merk.trim(), type: form.type.trim().toUpperCase() }; if (editingId) await updateFuelReference(editingId, input); else await createFuelReference(input); toast.add({ type: "success", title: editingId ? "Acuan fuel diperbarui" : "Acuan fuel ditambahkan", description: "Nilai dapat dipilih saat input operasional." }); reset(); setOpen(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Fuel reference gagal disimpan."); } finally { setSaving(false); } };
  const remove = async (row: FuelReference) => { if (!window.confirm(`Hapus acuan fuel ${row.type}?`)) return; try { await deleteFuelReference(row.id); toast.add({ type: "success", title: "Acuan fuel dihapus", description: `${row.type} tidak lagi tersedia.` }); await load(); } catch (cause) { const detail = cause instanceof Error ? cause.message : "Fuel reference gagal dihapus."; setError(detail); toast.add({ type: "error", title: "Gagal menghapus acuan fuel", description: detail }); } };
  const field = (key: "average" | "low" | "mid" | "high", label: string) => <label className="block"><span className="text-xs font-semibold text-slate-700">{label}</span><input required min="0" step="0.01" type="number" value={form[key]} onChange={(event) => setForm({ ...form, [key]: Number(event.target.value) })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-400" /></label>;
  return <DashboardShell activeFeature={7}><div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-600">Data Management · Master 03</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Master Fuel Reference</h2><p className="mt-1 text-sm text-slate-500">Kelola acuan konsumsi OEM untuk setiap aktivitas.</p></div><div className="flex gap-2"><button type="button" onClick={() => { reset(); setOpen(true); }} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white shadow-sm hover:bg-blue-700"><Plus className="size-3.5" />Tambah acuan fuel</button><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-sm"><RefreshCw className="size-3.5" />Perbarui</button></div></section>
    <button type="button" aria-label="Tutup modal" onClick={() => setOpen(false)} className={`${open ? "fixed" : "hidden"} inset-0 z-40 cursor-default bg-slate-950/30`} /><form onSubmit={submit} className={`${open ? "fixed" : "hidden"} left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl sm:p-6`}><button type="button" aria-label="Tutup form fuel reference" onClick={() => { reset(); setOpen(false); }} className="absolute right-4 top-4 inline-flex size-8 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100"><X className="size-4" /></button><div className="mb-5 flex items-center gap-3 pr-8"><span className="rounded-xl bg-cyan-50 p-2.5 text-cyan-700"><Fuel className="size-5" /></span><div><h3 className="font-bold text-slate-950">{editingId ? "Edit Fuel Reference" : "Tambah Fuel Reference"}</h3><p className="mt-1 text-xs text-slate-500">Nilai rata-rata dan rentang dipakai sebagai acuan OEM.</p></div></div><div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-xs font-semibold text-slate-700">Merk / model</span><input required value={form.merk} onChange={(event) => setForm({ ...form, merk: event.target.value })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-400" /></label><label className="block"><span className="text-xs font-semibold text-slate-700">Tipe referensi</span><input required value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value.toUpperCase() })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 font-mono text-sm outline-none focus:border-blue-400" /></label></div><label className="block"><span className="text-xs font-semibold text-slate-700">Aktivitas</span><select value={form.activity} onChange={(event) => setForm({ ...form, activity: event.target.value })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none">{activities.map((activity) => <option key={activity} value={activity}>{activity}</option>)}</select></label><div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{field("average", "Rata-rata")}{field("low", "Low")}{field("mid", "Mid")}{field("high", "High")}</div></div><button type="submit" disabled={saving} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white hover:bg-blue-700 disabled:opacity-50">{saving ? <LoaderCircle className="size-3.5 animate-spin" /> : editingId ? <Check className="size-3.5" /> : <Plus className="size-3.5" />}{editingId ? "Simpan perubahan" : "Tambah acuan fuel"}</button>{error && <p className="mt-3 text-xs font-semibold text-rose-600">{error}</p>}</form>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:p-6"><div><h3 className="font-bold text-slate-950">Daftar Acuan Fuel</h3><p className="mt-1 text-xs text-slate-500">{rows.length} dari {items.length} acuan.</p></div><DataTableSearch value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Cari tipe, merk, aktivitas..." /></div><div className="overflow-x-auto">{loading ? <div className="flex h-48 items-center justify-center"><LoaderCircle className="size-6 animate-spin text-cyan-600" /></div> : <table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3"><SortableHeader label="Tipe / Merk" active={sortKey === "type"} direction={sortDirection} onClick={() => toggleSort("type")} /></th><th className="px-5 py-3"><SortableHeader label="Aktivitas" active={sortKey === "activity"} direction={sortDirection} onClick={() => toggleSort("activity")} /></th><th className="px-5 py-3 text-right"><SortableHeader label="Rata-rata" align="right" active={sortKey === "average"} direction={sortDirection} onClick={() => toggleSort("average")} /></th><th className="px-5 py-3 text-right">Rentang low · mid · high</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleRows.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-mono font-bold text-slate-800">{row.type}</p><p className="mt-1 text-[10px] text-slate-400">{row.merk}</p></td><td className="px-5 py-4 capitalize text-slate-600">{row.activity}</td><td className="px-5 py-4 text-right font-mono font-bold text-slate-800">{number(row.average)} L/hr</td><td className="px-5 py-4 text-right font-mono text-slate-600">{number(row.low)} · {number(row.mid)} · {number(row.high)}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={() => edit(row)} className="rounded-xl border border-amber-200 bg-amber-50 p-2 text-amber-700 hover:bg-amber-100"><Pencil className="size-3.5" /></button><button type="button" onClick={() => void remove(row)} className="rounded-xl border border-rose-200 bg-rose-50 p-2 text-rose-700 hover:bg-rose-100"><Trash2 className="size-3.5" /></button></div></td></tr>)}</tbody></table>}{!loading && rows.length === 0 && <p className="p-10 text-center text-sm text-slate-400">Data tidak ditemukan.</p>}</div>{!loading && <DataTablePagination page={page} pageCount={pageCount} total={rows.length} pageSize={pageSize} onPageChange={setPage} />}</section>
  </div></DashboardShell>;
}
