"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Check, LoaderCircle, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { createContractor, deleteContractor, fetchContractors, updateContractor } from "@/lib/api";
import type { Contractor, ContractorCreateInput } from "@/types/api";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { DataTablePagination, DataTableSearch, SortableHeader, type SortDirection } from "@/components/ui/data-table";
import { toast } from "@/components/ui/toast";

const emptyForm: ContractorCreateInput = { code: "", company_name: "", status: "active" };
const pageSize = 10;
type SortKey = "code" | "company_name" | "status";

export function MasterContractorsClient() {
  const [items, setItems] = useState<Contractor[]>([]);
  const [form, setForm] = useState<ContractorCreateInput>(emptyForm);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [sortKey, setSortKey] = useState<SortKey>("code");
  const [sortDirection, setSortDirection] = useState<SortDirection>("asc");
  const [page, setPage] = useState(1);

  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await fetchContractors()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Data kontraktor tidak dapat dimuat."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const reset = () => { setForm(emptyForm); setEditingId(null); };
  const toggleSort = (key: SortKey) => { setSortDirection((current) => sortKey === key && current === "asc" ? "desc" : "asc"); setSortKey(key); setPage(1); };
  const rows = useMemo(() => items.filter((item) => `${item.code} ${item.company_name} ${item.status}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => String(a[sortKey]).localeCompare(String(b[sortKey]), "id", { numeric: true }) * (sortDirection === "asc" ? 1 : -1)), [items, query, sortDirection, sortKey]);
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize));
  const visibleRows = rows.slice((Math.min(page, pageCount) - 1) * pageSize, Math.min(page, pageCount) * pageSize);

  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(null); try { if (editingId) await updateContractor(editingId, { company_name: form.company_name.trim(), status: form.status }); else await createContractor({ code: form.code.trim(), company_name: form.company_name.trim(), status: form.status }); toast.add({ type: "success", title: editingId ? "Kontraktor diperbarui" : "Kontraktor ditambahkan", description: "Perubahan berhasil disimpan." }); reset(); setModalOpen(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Data kontraktor gagal disimpan."); } finally { setSaving(false); } };
  const edit = (item: Contractor) => { setEditingId(item.id); setForm({ code: item.code, company_name: item.company_name, status: item.status }); setError(null); setModalOpen(true); };
  const remove = async (item: Contractor) => { if (!window.confirm(`Hapus kontraktor ${item.company_name}?`)) return; try { await deleteContractor(item.id); toast.add({ type: "success", title: "Kontraktor dihapus", description: `${item.company_name} berhasil dihapus.` }); await load(); } catch (cause) { const detail = cause instanceof Error ? cause.message : "Kontraktor gagal dihapus."; setError(detail); toast.add({ type: "error", title: "Gagal menghapus kontraktor", description: detail }); } };

  return <DashboardShell activeFeature={4}><div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-600">Data Management · Master 01</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Master Kontraktor</h2><p className="mt-1 text-sm text-slate-500">Kelola perusahaan kontraktor yang menjadi dasar analisis multi-kontraktor.</p></div><div className="flex gap-2"><button type="button" onClick={() => { reset(); setModalOpen(true); }} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white shadow-sm hover:bg-blue-700"><Plus className="size-3.5" />Tambah kontraktor</button><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-sm hover:border-cyan-300 hover:text-cyan-700"><RefreshCw className="size-3.5" />Perbarui</button></div></section>
    <button type="button" aria-label="Tutup modal" onClick={() => setModalOpen(false)} className={`${modalOpen ? "fixed" : "hidden"} inset-0 z-40 cursor-default bg-slate-950/30`} /><form onSubmit={submit} className={`${modalOpen ? "fixed" : "hidden"} left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-md -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl sm:p-6`}><button type="button" aria-label="Tutup form kontraktor" onClick={() => { reset(); setModalOpen(false); }} className="absolute right-4 top-4 inline-flex size-8 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100"><X className="size-4" /></button><div className="mb-5 flex items-center gap-3 pr-8"><span className="rounded-xl bg-cyan-50 p-2.5 text-cyan-600"><Building2 className="size-5" /></span><div><h3 className="font-bold text-slate-950">{editingId ? "Edit Kontraktor" : "Tambah Kontraktor"}</h3><p className="mt-1 text-xs text-slate-500">Data wajib untuk relasi equipment.</p></div></div><div className="space-y-4"><label className="block"><span className="text-xs font-semibold text-slate-700">Kode kontraktor</span><input required disabled={editingId !== null} value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-cyan-400" /></label><label className="block"><span className="text-xs font-semibold text-slate-700">Nama perusahaan</span><input required value={form.company_name} onChange={(event) => setForm({ ...form, company_name: event.target.value })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-cyan-400" /></label><label className="block"><span className="text-xs font-semibold text-slate-700">Status</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-cyan-400"><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><button type="submit" disabled={saving} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white hover:bg-blue-700 disabled:opacity-50">{saving ? <LoaderCircle className="size-3.5 animate-spin" /> : editingId ? <Check className="size-3.5" /> : <Plus className="size-3.5" />}{editingId ? "Simpan perubahan" : "Tambah kontraktor"}</button>{error && <p className="mt-3 text-xs font-semibold text-rose-600">{error}</p>}</form>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:p-6"><div><h3 className="text-base font-bold text-slate-950">Daftar Kontraktor</h3><p className="mt-1 text-xs text-slate-500">{rows.length} dari {items.length} kontraktor.</p></div><DataTableSearch value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Cari kode atau perusahaan..." /></div><div className="overflow-x-auto">{loading ? <div className="flex h-48 items-center justify-center"><LoaderCircle className="size-6 animate-spin text-cyan-500" /></div> : <table className="w-full min-w-[620px] text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3"><SortableHeader label="Kode" active={sortKey === "code"} direction={sortDirection} onClick={() => toggleSort("code")} /></th><th className="px-5 py-3"><SortableHeader label="Perusahaan" active={sortKey === "company_name"} direction={sortDirection} onClick={() => toggleSort("company_name")} /></th><th className="px-5 py-3"><SortableHeader label="Status" active={sortKey === "status"} direction={sortDirection} onClick={() => toggleSort("status")} /></th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleRows.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-mono font-bold text-slate-700">{item.code}</td><td className="px-5 py-4 font-semibold text-slate-800">{item.company_name}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${item.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{item.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={() => edit(item)} title="Edit" className="rounded-xl border border-amber-200 bg-amber-50 p-2 text-amber-700 hover:bg-amber-100"><Pencil className="size-3.5" /></button><button type="button" onClick={() => void remove(item)} title="Hapus" className="rounded-xl border border-rose-200 bg-rose-50 p-2 text-rose-700 hover:bg-rose-100"><Trash2 className="size-3.5" /></button></div></td></tr>)}</tbody></table>}{!loading && rows.length === 0 && <p className="p-10 text-center text-sm text-slate-400">Data tidak ditemukan.</p>}</div>{!loading && <DataTablePagination page={page} pageCount={pageCount} total={rows.length} pageSize={pageSize} onPageChange={setPage} />}</section>
  </div></DashboardShell>;
}
